// Licensed under the MIT license.

export interface UserCreatedResponseOutput {
  /** An autogenerated unique id for the user */
  readonly id: number;
  /** The user's username */
  username: string;
  /** The user's email address */
  email: string;
  /**
   * The user's password, provided when creating a user
   * but is otherwise not visible (and hashed by the backend)
   */
  password: string;
  /** Whether the user is validated. Never visible to the API. */
  validated: boolean;
  /** The token to use to construct the validate email address url */
  token: string;
}

/** The user already exists */
export interface UserExistsResponseOutput extends ApiErrorOutput {
  code: "user-exists";
}

export interface ApiErrorOutput {
  /** A machine readable error code */
  code: string;
  /** A human readable message */
  message: string;
}

/** The user is invalid (e.g. forgot to enter email address) */
export interface InvalidUserResponseOutput extends ApiErrorOutput {
  code: "invalid-user";
}

export interface TodoPageOutput {
  /** The items in the page */
  items: Array<TodoItemOutput>;
  pagination: {
    pageSize: number;
    totalSize: number;
    prevLink?: string;
    nextLink?: string;
  };
}

export interface TodoItemOutput {
  /** The item's unique id */
  readonly id: number;
  /** The item's title */
  title: string;
  /** User that created the todo */
  readonly createdBy: number;
  /** User that the todo is assigned to */
  assignedTo?: number;
  /** A longer description of the todo item in markdown format */
  description?: string;
  /** The status of the todo item */
  status: "NotStarted" | "InProgress" | "Completed";
  /** When the todo item was created. */
  readonly createdAt: string;
  /** When the todo item was last updated */
  readonly updatedAt: string;
  /** When the todo item was makred as completed */
  readonly completedAt?: string;
  labels?: TodoLabelsOutput;
  _dummy?: string;
}

export interface TodoLabelRecordOutput {
  name: string;
  color?: string;
}

export interface TodoFileAttachmentOutput {
  /** The todo item this is attached to */
  readonly todoItemId: number;
  /** The file name of the attachment */
  filename: string;
  /** The media type of the attachment */
  mediaType: string;
  /** The url where the attachment can be downloaded from */
  readonly url: string;
  /** The contents of the file */
  contents: string;
}

export interface TodoUrlAttachmentOutput {
  /** A description of the URL */
  description: string;
  /** The url */
  url: string;
}

/** Alias for TodoLabelsOutput */
export type TodoLabelsOutput =
  | string
  | string[]
  | TodoLabelRecordOutput
  | Array<TodoLabelRecordOutput>;
/** Alias for TodoAttachmentOutput */
export type TodoAttachmentOutput =
  | TodoFileAttachmentOutput
  | TodoUrlAttachmentOutput;
