/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InvalidTodoItemJson = ApiErrorJson & {
  statusCode: 422;
};

export interface ApiErrorJson {
  /**
   * A machine readable error code
   */
  code: string;
  /**
   * A human readable message
   */
  message: string;
}
