/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TodoAttachmentJson = TodoFileAttachmentJson | TodoUrlAttachmentJson;

export interface TodoFileAttachmentJson {
  /**
   * The todo item this is attached to
   */
  todoItemId: number;
  /**
   * The file name of the attachment
   */
  filename: string;
  /**
   * The media type of the attachment
   */
  mediaType: string;
  /**
   * The url where the attachment can be downloaded from
   */
  url: string;
  /**
   * The contents of the file
   */
  contents: string;
}
export interface TodoUrlAttachmentJson {
  /**
   * A description of the URL
   */
  description: string;
  /**
   * The url
   */
  url: string;
}
