/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TodoFileAttachmentJson {
  /**
   * The file name of the attachment
   */
  filename: string;
  /**
   * The media type of the attachment
   */
  mediaType: string;
  /**
   * The contents of the file
   */
  contents: string;
}
