/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TodoItemPatchJson {
  /**
   * The item's title
   */
  title?: string;
  /**
   * User that the todo is assigned to
   */
  assignedTo?: number | null;
  /**
   * A longer description of the todo item in markdown format
   */
  description?: string | null;
  /**
   * The status of the todo item
   */
  status?: "NotStarted" | "InProgress" | "Completed";
}
