/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TodoLabelsJson = string | string[] | TodoLabelRecordJson | TodoLabelRecordJson[];

export interface TodoPageJson {
  /**
   * The items in the page
   */
  items: TodoItemJson[];
  pagination: {
    /**
     * The number of items returned in this page
     */
    pageSize: number;
    /**
     * The total number of items
     */
    totalSize: number;
    /**
     * The limit to the number of items
     */
    limit?: number;
    /**
     * The offset to start paginating at
     */
    offset?: number;
    /**
     * A link to the previous page, if it exists
     */
    prevLink?: string;
    /**
     * A link to the next page, if it exists
     */
    nextLink?: string;
  };
}
export interface TodoItemJson {
  /**
   * The item's unique id
   */
  id: number;
  /**
   * The item's title
   */
  title: string;
  /**
   * User that created the todo
   */
  createdBy: number;
  /**
   * User that the todo is assigned to
   */
  assignedTo?: number;
  /**
   * A longer description of the todo item in markdown format
   */
  description?: string;
  /**
   * The status of the todo item
   */
  status: "NotStarted" | "InProgress" | "Completed";
  /**
   * When the todo item was created.
   */
  createdAt: string;
  /**
   * When the todo item was last updated
   */
  updatedAt: string;
  /**
   * When the todo item was makred as completed
   */
  completedAt?: string;
  labels?: TodoLabelsJson;
  _dummy?: string;
}
export interface TodoLabelRecordJson {
  name: string;
  color?: string;
}
